# Generated by Django 5.2.4 on 2025-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication_app', '0002_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
