# Generated by Django 5.2.4 on 2025-07-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Role',
            new_name='role',
        ),
    ]
